name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'my_own_blog/package-lock.json'

      - name: Install dependencies
        working-directory: ./my_own_blog
        run: npm ci

      - name: Debug environment variables
        working-directory: ./my_own_blog
        env:
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_ATHLETE_ID: ${{ secrets.STRAVA_ATHLETE_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
        run: |
          echo "STRAVA_CLIENT_ID is set: $([[ -n $STRAVA_CLIENT_ID ]] && echo 'yes' || echo 'no')"
          echo "STRAVA_CLIENT_ID length: ${#STRAVA_CLIENT_ID}"
          echo "STRAVA_ATHLETE_ID is set: $([[ -n $STRAVA_ATHLETE_ID ]] && echo 'yes' || echo 'no')"
          echo "STRAVA_CLIENT_SECRET is set: $([[ -n $STRAVA_CLIENT_SECRET ]] && echo 'yes' || echo 'no')"
          echo "STRAVA_REFRESH_TOKEN is set: $([[ -n $STRAVA_REFRESH_TOKEN ]] && echo 'yes' || echo 'no')"

      - name: Build
        working-directory: ./my_own_blog
        env:
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_ATHLETE_ID: ${{ secrets.STRAVA_ATHLETE_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './my_own_blog/build'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
